<?php

/**
 * @file
 * Contains leadgen_paragraphs.module..
 */

/**
 * Implements hook_theme().
 */
function leadgen_paragraphs_theme() {
  $theme = [
    'leadgen_paragraphs_tab' => [
      'variables' => [
        'tab_titles' => [],
        'tab_text' => [],
      ],
    ],
    'leadgen_paragraphs_grid' => [
      'variables' => [
        'items' => [],
        'col_width' => [],
      ],
    ],
  ];

  return $theme;
}

/**
 * Implements hook_preprocess_paragraph__banner().
 */
function leadgen_paragraphs_preprocess_paragraph__banner(&$variables) {
  /** @var \Drupal\leadgen_paragraphs\BannerParagraph $banner_renderer */
  $banner_renderer = \Drupal::service('leadgen_paragraphs.banner');
  $banner_renderer->render($variables);
}

/**
 * Implements hook_preprocess_paragraph__carousel().
 */
function leadgen_paragraphs_preprocess_paragraph__carousel(&$variables) {
  /** @var \Drupal\leadgen_paragraphs\CarouselParagraph $carousel_renderer */
  $carousel_renderer = \Drupal::service('leadgen_paragraphs.carousel');
  $carousel_renderer->render($variables);
}

/**
 * Implements hook_preprocess_paragraph__tab().
 */
function leadgen_paragraphs_preprocess_paragraph__tab(&$variables) {
  /** @var \Drupal\leadgen_paragraphs\TabParagraph $tab_renderer */
  $tab_renderer = \Drupal::service('leadgen_paragraphs.tab');
  $tab_renderer->render($variables);
}

/**
 * Implements hook_preprocess_paragraph__grid().
 */
function leadgen_paragraphs_preprocess_paragraph__grid(&$variables) {
  /** @var \Drupal\leadgen_paragraphs\GridParagraph $grid_renderer */
  $grid_renderer = \Drupal::service('leadgen_paragraphs.grid');
  $grid_renderer->render($variables);
}
